services:
  postgres:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: forge3d
      POSTGRES_PASSWORD: forge3d_dev
      POSTGRES_DB: forge3d
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  meilisearch:
    image: getmeili/meilisearch:v1.12
    ports:
      - "7700:7700"
    environment:
      MEILI_MASTER_KEY: forge3d_search_dev
      MEILI_ENV: development
    volumes:
      - msdata:/meili_data

volumes:
  pgdata:
  msdata:
